version: "3.8"

services: 
  # container name
  database:
    container_name: db-soundgood
    # bind mounts volume
    volumes: 
      - /home/joppe/KTH/data_lagring_project:/host_files
    image: postgres
    ports:
      - 5432:5432
    networks: 
      - soundgood
    environment: 
      - POSTGRES_PASSWORD=password
  
  app:
    container_name: app-soundgood
    build: docker/
    networks:
      - soundgood
    volumes: 
      - /home/joppe/KTH/data_lagring_project:/host_files
    stdin_open: true
    tty: true

networks: 
  soundgood:

